server: 
  port: 80
  servlet:
    context-path: /
  
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kayla?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    encoding: UTF-8

MD5Salt: longwang

imageFilePath: D:\\longwang\\data\\IdeaProjects\\Blog\\src\\main\\webapp\\static\\images\\
downloadImagePath:  D:\\longwang\\data\\IdeaProjects\\Blog\\src\\main\\webapp
lucenePath: D:\\longwang\\data\\IdeaProjects\\Blog\\lucene
